#ifndef BTLOCK_COMMAND_CODE_H
#define BTLOCK_COMMAND_CODE_H

#define CC_UNLOCK 0x20
#define CC_ADD_USER 0x08
#define CC_DEL_USER 0x60
#define CC_NEW_PWD 0x40
#define CC_INQUIRY 0x10
#define CC_ASK_VERI 0x01

#define MASK_3BIT 0xE0
#define MASK_5BIT 0xF8

#endif //BTLOCK_COMMAND_CODE_H
